blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/LinwoodDev/Luna/discussions
    about: Here you can create threads to ask questions and discuss with other users. This is not synced with any chat platform.
  - name: Linwood Matrix
    url: https://go.linwood.dev/discord
    about: Please ask and answer questions here. Synced with discord.
  - name: Linwood Discord
    url: https://go.linwood.dev/discord
    about: Please ask and answer questions here. Synced with matrix.
