name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["api", "cli"]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      if: matrix.project == 'cli'
      with:
        package_json_file: ${{ matrix.project }}/package.json
        run_install: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
